language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - npm install -g bower
  - phantomjs --version
  - bower --version

install:
  - npm install
  - bower install

script:
  - npm test

deploy:
- provider: azure_web_apps
  on: master
  file_glob: true
  file: "dist/"

- provider: azure_web_apps
  slot: develop
  on: develop
  file_glob: true
  file: "dist/"

- provider: azure_web_apps
  slot: release
  on: release_2.1.1
  file_glob: true
  file: "dist/"

- provider: azure_web_apps
  slot: testing
  on: retina-143-search-results-component
  file_glob: true
  file: "dist/"
