language: node_js

node_js:
  - "6"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm

# before_install:
#   - npm config set spin false
#   - npm install -g phantomjs-prebuilt
#   - npm install -g bower
#   - phantomjs --version
#   - bower --version
#
# install:
#   - npm install
#   - bower install

script:
  - mkdir dist
  - touch dist/afile3.txt

# after_success:
#   - sh scripts/build-app.sh

deploy:
  - provider: azure_web_apps
    on: master
    verbose: true
    skip_cleanup: true

  - provider: azure_web_apps
    slot: retina-app-develop
    on: develop
    verbose: true
    skip_cleanup: true

  - provider: azure_web_apps
    slot: retina-app-release
    on: release_3.0.0
    verbose: true
    skip_cleanup: true

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: retina-app-release
    local-dir: dist
    acl: public_read
    on: release_3.0.0
    region: us-east-2
    skip_cleanup: true

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: retina-app-devlop
    local-dir: dist
    acl: public_read
    on: develop
    region: us-east-2
    skip_cleanup: true

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: retina-app
    local-dir: dist
    acl: public_read
    on: master
    region: us-east-2
    skip_cleanup: true
