language: node_js

node_js:
  - "10"

sudo: false

cache:
  directories:
    - node_modules

install:
  - yarn --pure-lockfile

before_deploy:
  - if [ "$TRAVIS_BRANCH" = master ]; then yarn build; else yarn build:dev; fi

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: retina-develop-us-east-2
    local-dir: dist
    acl: public_read
    on: develop
    region: us-east-2
    skip_cleanup: true

  # - provider: s3
  #   access_key_id: $AWS_ACCESS_KEY_ID
  #   secret_access_key: $AWS_SECRET_ACCESS_KEY
  #   bucket: retina-us-east-1
  #   local-dir: dist
  #   acl: public_read
  #   on: master
  #   region: us-east-2
  #   skip_cleanup: true
