language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - npm install -g bower
  - phantomjs --version
  - bower --version

install:
  - npm install
  - bower install

script:
  - npm test

deploy:
  file_glob: true
  file: "dist/"
- provider: azure_web_apps
  on: master
- provider: azure_web_apps
  slot: retina-app-develop
  on: develop
- provider: azure_web_apps
  slot: retina-app-release
  on: release_2.1.1
- provider: azure_web_apps
  slot: retina-app-testing
  on: retina-143-search-results-component
