language: node_js

node_js:
  - "8"

sudo: false

cache:
  directories:
    - node_modules
    - $HOME/.npm

before_install:
  - npm config set spin false

install:
  - npm install

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: retina-app-release
    local-dir: dist
    acl: public_read
    on: release_3.0.0
    region: us-east-2
    skip_cleanup: true

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: retina-app-develop
    local-dir: dist
    acl: public_read
    on: develop
    region: us-east-2
    skip_cleanup: true

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: retina-app
    local-dir: dist
    acl: public_read
    on: master
    region: us-east-2
    skip_cleanup: true
