language: node_js

node_js:
  - "8"

sudo: false

cache:
  directories:
    - node_modules
    - $HOME/.npm

before_install:
  - npm config set spin false

install:
  - npm install

script:
  - npm test
