language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - npm install -g bower
  - phantomjs --version
  - bower --version

install:
  - npm install
  - bower install

before_script: "git fetch --unshallow || true && git fetch origin '+refs/heads/*:refs/remotes/origin/*'"

script:
  - npm test

before_deploy: "ember build"

deploy:
- provider: azure_web_apps
  on: master
  file_glob: true
  file: "dist/*"
  verbose: true

- provider: azure_web_apps
  slot: retina-app-develop
  on: develop
  file_glob: true
  file: "dist/*"
  verbose: true

- provider: azure_web_apps
  slot: retina-app-release
  on: release_2.1.1
  file_glob: true
  file: "dist/*"
  verbose: true

- provider: azure_web_apps
  slot: retina-app-testing
  on: retina-143-search-results-component
  file_glob: true
  file: "dist/*"
  verbose: true
